#+title: All Posts
#+HUGO_SECTION: en/post
#+HUGO_BASE_DIR: ~/hwiorn-blog
#+HUGO_WEIGHT: auto


* PKMS
** TODO 나의 지식관리 여정
지식관리를 사용한 것은 아마 2008년도 시점인 것으로 기억한다. 그때만 해도
디지털보단 작은 수첩을 갖고다니면서 기록하던 시점이었는데, GTD와 Emacs org 로
정리하는 것을 알게 되어, 디지털 기록을 한참 생각했었다. 하지만, GTD는 디지털
워크플로가 정립되어 있거나, 회사 생활을 하지 않는 이상 장기간 쓰기 힘들다는
점으로 인해, 철학에 너무 동의하지만 그 당시 환경과 맞지 않아, 쓰지
않았었다.(쓰고 싶어도 못썼다는 평가가 맞을 듯)

그러다가 에버노트, Firefox scrabbooks등을 써오면서 스크랩 위주의 데이터를
모으면서, 지식 관리를 해나갔다. 이 당시는 중요한 정보를 스크랩 하는 것이 나의
지식을 관리하는 것이라고 생각했다. 하지만, 에버노트는 유료였고, 리눅스나
모바일에서 쓸수 없다는 점이 단점이었고, 무료 프로그램은 외부 동기화가 어렵다는
점이 있어, 바꾸어 가면서 번갈아 사용했었다. 이때 데이터는 9:1정도로 압도적으로
스크랩 노트가 많았다.

에버노트 프로그램을 메인으로 쓰지 않게 되면서, 여러가지 지식관리 프로그램을
사용해봤었는데, 그러다가 에버노트가 정책을 바꾸기 시작하면서, 조플린으로
마이그레이션을 진행했고, 한동안 에버노트 대용으로 업무 내역 노트나 스크랩에
사용하였다.

이때까지는 Emacs를 주력으로 사용하다가, VSCode로 변경하던 시기였다.(큰 이유는 아니지만, Emacs가 한참 느려졌고, 주력 에디터를 변경하여 VS Code에 익숙해지려고 했던 이유가 있었음)

그러다가 2021년 숀케 아렌스의 제텔카스텐 책을 보게 되면서, 제텔카스텐에 흥미를 갖게 되었다. 그러면서 여러가지 도구를 다시 사
** TODO 나의 지식관리 도구
2023년 4월 26일 기준 PKMS에 사용하는 툴 목록이다.

현재 주력으로 사용하는 툴은 Emacs이며, 주 OS는 Linux 환경[fn:1]이고, 모바일은
아이폰[fn:2]을 사용한다.

- 캡쳐
  - 아날로그: 포켓수첩[fn:3]
  - PC: Emacs
  - Web: hypothes.is, reclipped
- 노트 작성
  - PC: Emacs
  - iOS: 안함
- 노트 정리

*** Footnotes

[fn:2] 주로 Emacs와 Linux를 쓰는 사용자는 안드로이드 기반을 사용하기 때문에,
iOS의 경우 관련 자료나 워크플로에 대한 글들이 많이 존재하지는 않는다.

[fn:1] Linux 환경을 주력으로 쓰는 이유는 입맛대로 쓰고 싶어서지만, iOS와 Windows
프로그램 개발을 했었기 때문에, 나름 다른 OS도 쓸수 있다. 아마 회사에서 쓴다면
맥을 사지 않을까 싶다.

[fn:3] 포켓 수첩은 양지사 PD90을 썼지만, 1달이상 쓰면 겉표지가 말그대로
쪼개진다. 그래서 지금은 미도리 패스포트 형태의 가죽 수첩을 사용한다. 속지는
한동안 미도리 호환을 쓰다가 지금은 다이소의 500원 수첩을 끼워서 사용하고 있다.
